version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=${APP_KEY} # Use APP_KEY from .env
            - DB_CONNECTION=pgsql
            - DB_HOST=aws-0-us-west-1.pooler.supabase.com # Supabase host
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres.oaxujrkdukrqvftqngsc
            - DB_PASSWORD=MudzzVCir4XjjMAx
