version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - storage:/var/www/html/storage
            - cache:/var/www/html/bootstrap/cache
        ports:
            - "8000:8000"
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - APP_KEY=SUMyYMGqYAPeAujwgaKlYZWGt32CUmtEf6SScctRixg=
            - DB_CONNECTION=pgsql
            - DB_HOST=aws-0-us-west-1.pooler.supabase.com
            - DB_PORT=5432
            - DB_DATABASE=postgres
            - DB_USERNAME=postgres.oaxujrkdukrqvftqngsc
            - DB_PASSWORD=MudzzVCir4XjjMAx
            - PORT=8000
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: laravel_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres.oaxujrkdukrqvftqngsc
            POSTGRES_PASSWORD: MudzzVCir4XjjMAx
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    storage:
    cache:
    pgdata:
